;; -*- lexical-binding: t -*-
(defun +elfeed-search-quit-and-kill-buffers ()
  "Save the database, then kill elfeed buffers, asking the user
for confirmation when needed."
  (interactive)
  (elfeed-db-save)
  (when (get-buffer "*elfeed-entry*")
    (kill-buffer "*elfeed-entry*"))
  (when (get-buffer "*elfeed-log*")
    (kill-buffer "*elfeed-log*"))
   (kill-buffer (current-buffer)))

(use-package elfeed
  :straight t
  :init
(setq elfeed-feeds
'(
"https://www.cambridge.org/core/rss/product/id/49AD4731AAB0E94D8EF98BBB4EE56A7F"
"http://blog.ezyang.com/feed/"
"http://feeds.feedburner.com/PythonInsider"
"http://feeds.woboq.com/woboq"
"http://funcall.blogspot.com/feeds/posts/default?alt=rss"
"http://kroah.com/log/index.rss"
"http://p-cos.blogspot.com/feeds/posts/default?alt=rss"
"http://research.swtch.com/feed.atom"
"http://wcook.blogspot.com/feeds/posts/default?alt=rss"
"http://www.greghendershott.com/feeds/all.atom.xml"
"http://www.invece.org/rss"
"http://www.kroah.com/log/index.rss"
"https://asaba.sakuragawa.moe/feed/"
"https://benjamincongdon.me/blog/feed.xml"
"https://blog.codingnow.com/atom.xml"
"https://blog.feabhas.com/feed/"
"https://blog.jabref.org/feed.xml"
"https://blog.lilydjwg.me/feed"
"https://blog.petdance.com/feed.xml"
"https://blog.sgorava.xyz/index.xml"
"https://ctian.livejournal.com/data/rss"
"https://daniel.haxx.se/blog/feed/"
"https://devblogs.microsoft.com/oldnewthing/author/oldnewthing/feed"
"https://dot.kde.org/rss.xml"
"https://dr-knz.net/feeds/all.rss.xml"
"https://drewdevault.com/blog/index.xml"
"https://eliasdaler.github.io/feed.xml"
"https://farseerfc.me/feeds/atom.xml"
"https://feeds.feedburner.com/2ality"
"https://feeds.feedburner.com/abseilio"
"https://hpjansson.org/blag/feed/"
"https://iscinumpy.gitlab.io/index.xml"
"https://isocpp.org/blog/rss"
"https://linuxreviews.org/feed.rss"
"https://lucumr.pocoo.org/feed.atom"
"https://martinfowler.com/feed.atom"
"https://matklad.github.io/feed.xml"
"https://matt.might.net/articles/feed.rss"
"https://michaelnielsen.org/blog/feed/"
"https://netcan.github.io/atom.xml"
"https://nullprogram.com/feed/"
"https://oleksandrkvl.github.io/feed.xml"
"https://planet.kde.org/global/atom.xml"
"https://pockies.github.io/feed.xml"
"https://preshing.com/feed"
"https://purinchu.net/wp/feed/feed.xml"
"https://raphlinus.github.io/feed.xml"
"https://ridiculousfish.com/blog/atom.xml"
"https://rosenzweig.io/feed.xml"
"https://sh.alynx.one/atom.xml"
"https://utcc.utoronto.ca/~cks/space/blog/?atom"
"https://vermaden.wordpress.com/feed/"
"https://www.alanshawn.com/atom.xml"
"https://www.cppstories.com/index.xml"
"https://www.csslayer.info/wordpress/feed/"
"https://www.internalpointers.com/rss"
"https://www.lyx.org/misc/rss/lyx_news_feed.xml"
"https://www.magicsplat.com/blog/rss.xml"
"https://www.nayuki.io/rss20.xml"
"https://dave.cheney.net/feed/atom"
"https://herbsutter.com/feed/"
"https://blog.shaynefletcher.org/feeds/posts/default"
"https://dthompson.us/feed.xml"
"https://blog.nelhage.com/atom.xml"
"https://weinholt.se/feed.xml"
"http://jakob.space/feed.xml"
"http://planet.lisp.org/rss20.xml"
"https://tymoon.eu/api/reader/atom"
"https://neovim.io/news.xml"
"https://fare.livejournal.com/data/rss"
"http://www.pixelbeat.org/feed/rss2.xml"
"https://sfconservancy.org/feeds/blog/"
"https://tenthousandmeters.com/feeds/all.atom.xml"
"https://betterexplained.com/feed/"
"https://eli.thegreenplace.net/feeds/all.atom.xml"
"https://www.craigfe.io/feed.xml"
"http://www.lispology.com/rss?JHE+3"
"https://www.ocamlpro.com/feed/"
"https://fsharpforfunandprofit.com/index.xml"
"https://inside.java/feed.xml"
"http://lambda-the-ultimate.org/rss.xml"
"https://slbtty.gitlab.io/feed.xml"
"http://jakob.space/feed.xml"
"https://www.more-magic.net/feed.atom"
"https://tess.oconnor.cx/feed"
"http://modernescpp.com/?format=feed&type=rss"
"http://neugierig.org/software/blog/atom.xml"
"https://64k.space/feed.xml"
"https://code.visualstudio.com/feed.xml"
"https://www.murilopereira.com/index.xml"
"https://planet.emacslife.com/atom.xml"
"https://borretti.me/feed.xml"
"http://www.weaselhat.com/feed/"
"https://blog.sigplan.org/feed/"
"https://www.stephendiehl.com/feed.atom"
"https://blog.gtk.org/feed/"
"https://crascit.com/feed/"
"https://lemire.me/blog/feed/"
"https://popey.com/blog/index.xml"
"https://weekly.nixos.org/feeds/all.atom.xml"
"https://racket-news.com/feeds/all.atom.xml"
"https://lexi-lambda.github.io/feeds/all.atom.xml"
"https://okmij.org/ftp/rss.xml"
"https://gretzuni.com/atom/"
"http://www.turtleware.eu/rss.xml"
"https://writings.stephenwolfram.com/feed/"
"https://defn.io/index.xml"
"https://wadler.blogspot.com/feeds/posts/default"
"http://www.randomhacks.net/feed.xml"
"http://lambda-the-ultimate.org/rss.xml"
"http://xahlee.info/emacs/emacs/blog.xml"
"https://alarmingdevelopment.org/?feed=rss2"
"https://www.logicmatters.net/feed/"
"https://pythonspeed.com/atom.xml"
"https://cprss.s3.amazonaws.com/golangweekly.com.xml"
"https://developer.ibm.com/technologies/linux/feed/"
"https://factorio.com/blog/rss"
"https://stackoverflow.com/feeds/user/2625442"
"https://blog.shaynefletcher.org/feeds/posts/default"
"https://www.haskellforall.com/feeds/posts/default"
"https://planet.scheme.org/atom.xml"
"https://programmingpraxis.com/feed/"
"https://cstheory.stackexchange.com/feeds/user/2185"
"http://math.andrej.com/feed.xml"
"https://blog.system76.com/rss"
"https://jao.io/blog/rss.xml"
"https://countvajhula.com/feed/"
"https://sachachua.com/blog/feed"
"https://semantic-domain.blogspot.com/feeds/posts/default"
"https://alan.petitepomme.net/cwn/cwn.rss"
"https://cacm.acm.org/magazine.rss"
"https://0pointer.net/blog/index.atom"
"https://danlark.org/feed/"
;; extras after migration
"https://engineering.fb.com/feed/"
"https://spwhitton.name/blog/index.atom"
"https://darkcoding.net/index.xml"
"https://justinmeiners.github.io/feed.xml"
"https://chaoxuprime.com/rss.xml"
"https://jgrulich.cz/feed/"
))
:config
(setq-default elfeed-search-filter "@1-years-ago")
:bind
(:map elfeed-search-mode-map
      ("o" . #'elfeed-search-browse-url)
      ("<escape>" . +elfeed-search-quit-and-kill-buffers)
 :map elfeed-show-mode-map
      ("o" . elfeed-show-visit)
      ("b" . (lambda () (interactive) (switch-to-buffer "*elfeed-search*"))))
;;(define-key elfeed-show-mode-map (kbd "o") 'elfeed-show-visit)
;;(define-key  (kbd "o") 'elfeed-search-browse-url)
)
