#!/bin/bash

set -e

SCRIPT=$(realpath "$0") # -> Complete path /home/slbtty/scripts/sourcetest.bash
SCRIPTPATH=$(dirname "$SCRIPT") #-> only /home/slbtty/scripts

function _color_echo()
{
  echo -e "\e[0;$1m> $2\e[0m"
}

# Note: - maybe invlid for some shell env
function red-msg(){ 
    _color_echo "31" "$1";
}

function green-msg(){ 
    echo -e "\033[1;32m > $1 \e[0m"
}

function blue-msg(){ 
_color_echo "34" "$1";
}

# $1 -> Path to file inside git
# $2 -> Path to system target 
function link_file2(){
    homeloc="${HOME}/${1}"
    scrploc="${SCRIPTPATH}/home/${1}"
if [ ! -f "$scrploc" ];
then
    red-msg "$scrploc doesn't exist"
    blue-msg "Trying to copy it from $homeloc"
    if [ -f "$homeloc" ]; 
    then
        green-msg "Copying $homeloc to $scrploc"
        dirloc=$(dirname "$scrploc")
        mkdir -p "$dirloc" &&  cp "$homeloc" "$scrploc"
    else 
        red-msg "$homeloc doesn't exist too!"
        return;
    fi 
fi

if [ -f "$homeloc" ];
then
    # TODO: detect broken link is possible
    if [ "$(file --mime-type --brief "$1")" == "inode/symlink" ];then
        green-msg "${1} is already linked!"
        return;
    else 
        blue-msg "Remove original $homeloc"
        rm "$homeloc"
    fi
else
    green-msg "No $homeloc at home"
fi
ln -sf "$scrploc" "$homeloc"
green-msg "Link ${homeloc} to ${scrploc}"
}

function link_dir(){
    # ln -s cannot create directories automatically :(
    mkdir -p "${HOME}/${1}"
}

link_file2 ".bashrc"
link_file2 ".bash_profile"
link_file2 ".newsboat/config"

link_dir ".config/ranger"
link_file2 ".config/ranger/rc.conf"
link_file2 ".config/ranger/rifle.conf"



link_dir ".config/sublime-text/Packages/User"
link_file2 ".config/sublime-text/Packages/User/Preferences.sublime-settings"
link_file2 ".config/sublime-text/Packages/User/Package Control.sublime-settings"
link_file2 ".config/sublime-text/Packages/User/Terminus.sublime-settings"

#lisp related
link_file2 ".sbclrc"

#editors
link_file2 ".spacemacs"

link_dir ".doom.d"
link_file2 ".doom.d/init.el"
link_file2 ".doom.d/config.el"
link_file2 ".doom.d/packages.el"

link_file2 ".vimrc"

link_dir ".config/nvim"
link_file2 ".config/nvim/init.vim"
link_file2 ".config/nvim/ginit.vim"

