#!/usr/bin/env bash

set -e
function green-msg(){ 
    echo -e "\e[0;32m[slb] $1\e[0m"
}

if command -v racket &> /dev/null
then
    green-msg "Racked already installed :)"
    exit 0
fi

OSNAME=$(awk -F= '/^NAME/{gsub(/"/, "", $2);print $2}' /etc/os-release)

for i in "KDE neon" "Ubuntu"
do
    if [ "$i" == "$OSNAME" ]
    then
        C_OSNAME="ubuntu"
        break 
    fi
done

blue-msg "Your os is $OSNAME -> $C_OSNAME"


case $C_OSNAME in
    ubuntu) 
        sudo add-apt-repository ppa:plt/racket
        sudo apt-get update
        sudo apt install racket
    ;;
esac
