#!/bin/bash

needed="base-devel \
git"

core="firefox \
noto-fonts-cjk \
vlc \
okular \
ark \
bash-completion \
shellcheck \
qt5-tools \
fuse \
hunspell \
hunspell-en_us \
newsboat \
xdg-desktop-portal-kde \
"

utl="fzf \
ack \
ncdu \
man-db \
"


sudo pacman -S --needed "${needed}"
sudo pacman -S "${core}"

#fonts

sudo pacman -S ttf-roboto
