#!/bin/bash
set -e
set -x

#<https://github.com/logological/gpp>

cd "${HOME}"
if [[ ! -d git-gpp ]];then
git clone git@github.com:logological/gpp.git git-gpp --depth=1
fi
cd "${HOME}"/git-gpp
autoreconf -i # autoconfig generate configure
./configure
make
sudo make install