# shell /usr/bin/fish

remember_window_size  no
initial_window_width  120c
initial_window_height 40c

text_fg_override_threshold 4.5 ratio
cursor_trail 3

tab_bar_edge top
tab_bar_style separator
tab_separator "  |  "

cursor_blink_interval 0
cursor_shape block

scrollback_lines 20000

allow_remote_control yes

map f1 detach_window ask
map f2 next_tab

map ctrl+] next_tab
map ctrl+[ previous_tab

map f3 new_tab_with_cwd
map f4 launch --type=overlay --stdin-source=@screen_scrollback fzf --no-sort --no-mouse --exact -i --tac
map f5 launch --type=overlay --stdin-source=@screen_scrollback --stdin-add-formatting  less +G -R

#os specific
# macos_titlebar_color background
macos_quit_when_last_window_closed yes
macos_option_as_alt yes

enabled_layouts tall,fat

include current-theme.conf
include local.conf
